### PR TITLE
Fixed user privileges in docker container to work in AWS

### PR DESCRIPTION
**Pull request by bdeining**

### CODE REVIEW

**Comment by willwill96** [comment]
:pencil2: `Fixed user privile`~~d~~`ges `in docker container to work in AWS`

**Comment by djblue** [comment]
What is this doing exactly?

**Comment by bdeining** [comment]
When the files are copied in docker they need to be owned by the user defined in the docker file (revelio) https://github.com/connexta/revelio/pull/172/files#diff-3254677a7917c6c01f55212f86c57fbfR4 otherwise they are owned by root and the revelio user cannot do anything with them

**Comment by bdeining** [comment]
https://docs.docker.com/engine/reference/builder/#copy

**Pull request merged**
